### ISSUE TITLE
publish to the Play Store

### ISSUE THREAD

**Issue by jawz101** [antoinepirlot/Satunes#601]
Android Auto itself requires all sorts of Google services support.  It makes sense to publish an app which uses Google's Android Auto onto the Play Store so users to not have to enable 3p apps onto Android Auto.

**Comment by antoinepirlot** [comment]
Hey, 

Thanks for reporting. ☺️

I know it's easier for the user to get apps from Google Play Store to skip the configuration with Android Auto but it's not in my projects to publish an app on Google Play Store. 🙂
