### ISSUE TITLE
Setup directories

### ISSUE THREAD

**Issue by braoult** [antoinepirlot/Satunes#602]
Is it possible to setup directories, so that the player is limited to search within them ? And have them read-only (they are synchronized daily) ?

For example, my structure (Android 13) is (all directories/filenames are UTF-8 encoded) :
```
/emulated/0/                             /* root directory         */
 - Music/
    - Music/                             /* Music folder to use    */
       - Artist | Composer/              /* Composer when suitable */
          - Album | Artist - Album/      /* Artist when suitable   */
             - XX Title.mp3              /* XX = track number      */
    - Playlists/                         /* Playlists, only M3U    */
       - Name.m3u
    - Ringtones/
    - [...]
```

It would be nice if Satunes could be configured to search its music/playlists only in `/emulated/0/Music/{Music,emulated}` directories (read-only), with maybe different read-write directory for Satunes-created playlists (e.g. . `/emulated/0/Music/XXX/`).

Note that all my `playlist.m3u` contains UTF-8-encoded entries with relative path to the mp3 file, for example :
```
#EXTM3U
#EXTINF:,Great Mass - Kyrie
../Music/Wolfgang Amadeus Mozart/Bernstein - Great Mass, Exsultate, jubilate, Ave verum corpus/03 Great Mass - Kyrie.mp3
[...]
#EXTINF:258,元ちとせ - この街 
../Music/元ちとせ/ノマド・ソウル/07 この街.mp3
```
I am preparing more reports, as I just started to try Satunes, and noticed some dysfunctions (including crashes). I just need more testing to give exact description...

**Comment by antoinepirlot** [comment]
Hey,

Thanks for reporting.

I'm sorry for bugs, it's my very first app.

To read only Music folder, I will check to refactor how music is loaded and simplify this for the user.

**Comment by antoinepirlot** [comment]
Hey,

Thanks for reporting.

I'm sorry for bugs, it's my very first app.

To read only Music folder, I will check to refactor how music is loaded and simplify this for the user.

For M3U files, I will check to support it. #329

**Comment by braoult** [comment]
In fact the main idea is to prevent the app to look for music in directories not specified (they could contain audio files, not intended for a Music player).

**Comment by antoinepirlot** [comment]
> In fact the main idea is to prevent the app to look for music in directories not specified (they could contain audio files, not intended for a Music player).

Yeah, at the beginning, I thought the library I use only returns the music in Music folder but that's not the case 🤡 I will change that

**Comment by antoinepirlot** [comment]
Satunes load only Music folder by default. Exclude Ringtones feature became Include Ringtones.
For the support of M3U see #329

**Comment by braoult** [comment]
I am not sure: Do you mean you mean hardcoding "Music" directory ?

This was not my point at all here, as I meant "user-defined" directories which should be used, excluding everything else.
If you look at my tree above, some "Music" folder sub-directories are included (two in my case, namely `Music/Music` and `Music/Playlists`), all other Music sub-directories should be ignored.

But it could be anything else, like `Music/Classical` or one folder up (e.g `Classical`).

Example, with 4 directories included :

        Music/
            Music/Music/                             *** included
            Music/Classical/                         *** included
            Music/Playlists/                         *** included
            Music/Ringtones/                         IGNORED
            Music/foo/                               IGNORED
            Music/test/                              IGNORED
        Syncthing/
            Syncthing/Music/Classical/               *** included
            Syncthing/foo                            IGNORED
        Music2/                                      *** included
        [etc...]

In Musicolet, the interface to define the directories to scan looks like :

![to-scan](https://github.com/user-attachments/assets/f680eef4-9345-4cec-aee4-986d492e8e72)

**Comment by antoinepirlot** [comment]
> I am not sure: Do you mean you mean hardcoding "Music" directory ?
> 
> This was not my point at all here, as I meant "user-defined" directories which should be used, excluding everything else. If you look at my tree above, some "Music" folder sub-directories are included (two in my case, namely `Music/Music` and `Music/Playlists`), all other Music sub-directories should be ignored.
> 
> But it could be anything else, like `Music/Classical` or one folder up (e.g `Classical`).
> 
> Example, with 4 directories included :
> 
> ```
>     Music/
>         Music/Music/                             *** included
>         Music/Classical/                         *** included
>         Music/Playlists/                         *** included
>         Music/Ringtones/                         IGNORED
>         Music/foo/                               IGNORED
>         Music/test/                              IGNORED
>     Syncthing/
>         Syncthing/Music/Classical/               *** included
>         Syncthing/foo                            IGNORED
>     Music2/                                      *** included
>     [etc...]
> ```
> 
> In Musicolet, the interface to define the directories to scan looks like :
> 
> ![to-scan](https://private-user-images.githubusercontent.com/8958429/350672383-f680eef4-9345-4cec-aee4-986d492e8e72.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NjI4ODksIm5iZiI6MTcyMTQ2MjU4OSwicGF0aCI6Ii84OTU4NDI5LzM1MDY3MjM4My1mNjgwZWVmNC05MzQ1LTRjZWMtYWVlNC05ODZkNDkyZThlNzIuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDA4MDMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YzUzODQ3NzMwYmUwMGIzOWRmMDI1MmY0NzczZjRmMGQ2YmQ1NTE1Mjc1OTZlYmJkYjRmMWUwNmUxY2UwNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4CehMsYFvNQ00gvIc9kQTBioNg50ySKvycV1ZM474l0)

Hmm, at this stage, I want to finish the code refactoring and try to make Satunes more stable.

Now, it's hard coded yeah as theoretically, Android has Ringtones folder alongside Music and not inside music. But I think to let the user add paths.

I won't add it in 2.0.0 as I already make big changes in code structure and I'm still adding some changes but I'll check to add it in 2.1.0 or 2.2.0.

**Comment by braoult** [comment]
OK. Stabilization first :-)

My point is that families having multiple devices (including their PCs) will likely synchronize **parts of** their music/playlists, hence the multiple directories.
