### ISSUE TITLE
Features i request

### ISSUE THREAD

**Issue by dan1471** [antoinepirlot/Satunes#617]
***Dark theme and omoled theme
***lyrics downloading and displaying
***New player design 
****Add theme selection

**Comment by antoinepirlot** [comment]
> ***Dark theme and omoled theme ***lyrics downloading and displaying ***New player design ****Add theme selection

Hey

Thanks for your comment ☺️.

Dark mode is already supported. For the AMOLED theme, that's a good idea, I think I will check to add it.

For the lyrics, I planned to integrate the lyrics from added to the file, firstly.

For the player design, I will check to add some animation and design rework but at this time, it won't change.

I didn't planned to add theme selection at this time but that's a good idea, I will think about it ☺️.

Thank you a lot for your interest in Satunes.

**Comment by dan1471** [comment]
I hope the features will be sooner...Thank you
