### ISSUE TITLE
SD Card Support Broken

### ISSUE THREAD

**Issue by Naomitr0n** [antoinepirlot/Satunes#731]
I have most of my music on my SD card, but none of it is showing up. Tried version 2.0.0-alpha 1 to see if #630 had any impact and it doesn't show up before that fix either, so support has never worked.

Sont Xperia 1 V (XQ-DQ62)
Android 14

Apollo, MD Player, Odyssey, etc. show up just fine. I believe it to be potentially related to Satunes' lack of `MANAGE_EXTERNAL_STORAGE` permission, which the others all have.

**Comment by antoinepirlot** [comment]
Hello, thanks for reporting. 

In fact, it's broken, it worked when I tested before deploying it 🙁.

I'm going to fix it as soon as possible.

Thank you

**Comment by antoinepirlot** [comment]
My bad, I tested on the preview version 😂.
I retest on the latest version (v2.0.1) and it works on my device with SD Card. 

Did you update Satunes to the latest version (v2.0.1)?

**Comment by Naomitr0n** [comment]
Unfortunately it's broken on 2.0.1 for me. That's the version I first checked out when I saw it pop up on F-Droid.

**Comment by Naomitr0n** [comment]
As per #732 (specifically, [this comment](https://github.com/antoinepirlot/Satunes/issues/732#issuecomment-2276749326)), SD support requires music be somewhere under `/Music`. Tested and working. Elsewhere on SD card doesn't work yet, however SD support in general does work, so closing this issue.

**Comment by antoinepirlot** [comment]
Pfiou 😮‍💨, happy to hear it works. ☺️ I'll add the paths selection soon
