### ISSUE TITLE
Corrupted File

### ISSUE THREAD

**Issue by macovei-alex** [antoinepirlot/Satunes#872]
I have had multiple issues where I accidentally generated a broken file/link in my phone which crashes the app when trying to open the app. It's no big deal as long as I find the file/link and delete it, but it is kind of annoying. I can't really tell you a sure way to generate such a file/link, but I did it once when trying and failing to download audio via NewPipe (this generated a file of size 0) and once after deleting an audio file (this generated a broken link that I found by searching for .mp3 files in my phone).

**Comment by antoinepirlot** [comment]
Hello, thanks for reporting.

Indeed, a 0 bytes mp3 files (and/or corrupted surely) will crash the app if loaded, that's a huge problem. 

I reproduced the issue, I will fix it as soon as possible 😉.

**Comment by antoinepirlot** [comment]
Fixed: releasing

**Comment by antoinepirlot** [comment]
It's fixed, I'm deploying a hotfix release
